# Generated by Django 4.2.1 on 2024-10-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('patologia', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('crm', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('especialidade', models.CharField(choices=[(1, 'Acupuntura'), (2, 'Alergia e Imunologia'), (3, 'Anestesiologia'), (4, 'Angiologia'), (5, 'Cardiologia'), (6, 'Cirurgia Cardiovascular'), (7, 'Cirurgia da Mão'), (8, 'Cirurgia de Cabeça e Pescoço'), (9, 'Cirurgia do Aparelho Digestivo'), (10, 'Cirurgia Geral'), (11, 'Cirurgia Oncológica'), (12, 'Cirurgia Pediátrica'), (13, 'Cirurgia Plástica'), (14, 'Cirurgia Torácica'), (15, 'Cirurgia Vascular'), (16, 'Clínica Médica'), (17, 'Coloproctologia'), (18, 'Dermatologia'), (19, 'Endocrinologia e Metabologia'), (20, 'Endoscopia'), (21, 'Gastroenterologia'), (22, 'Genética Médica'), (23, 'Geriatria'), (24, 'Ginecologia e Obstetrícia'), (25, 'Hematologia e Hemoterapia'), (26, 'Homeopatia'), (27, 'Infectologia'), (28, 'Mastologia'), (29, 'Medicina de Emergência'), (30, 'Medicina de Família e Comunidade'), (31, 'Medicina do Trabalho'), (32, 'Medicina de Tráfego'), (33, 'Medicina Esportiva'), (34, 'Medicina Física e Reabilitação'), (35, 'Medicina Intensiva'), (36, 'Medicina Legal e Perícia Médica'), (37, 'Medicina Nuclear'), (38, 'Medicina Preventiva e Social'), (39, 'Nefrologia'), (40, 'Neurocirurgia'), (41, 'Neurologia'), (42, 'Nutrologia'), (43, 'Oftalmologia'), (44, 'Oncologia Clínica'), (45, 'Ortopedia e Traumatologia'), (46, 'Otorrinolaringologia'), (47, 'Patologia'), (48, 'Patologia Clínica/ Medicina Laboratorial'), (49, 'Pediatria'), (50, 'Pneumologia'), (51, 'Psiquiatria'), (52, 'Radiologia e Diagnóstico por Imagem'), (53, 'Radioterapia'), (54, 'Reumatologia'), (55, 'Urologia')], max_length=3)),
            ],
            options={
                'unique_together': {('crm', 'estado')},
            },
        ),
    ]
