# Generated by Django 4.2.1 on 2024-10-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('dosagem', models.CharField(max_length=50)),
                ('unidade', models.CharField(max_length=10)),
            ],
        ),
    ]
